apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: social-network-activities
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activity-service
      version: blue
  template:
    metadata:
      labels:
        app: activity-service
        version: blue
    spec:
      serviceAccountName: activity-service-sa
      containers:
        - name: activity-service
          image: activity-service:latest
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: "mongodb.social-network-db"
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "activity_db"
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
            - name: SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE
              value: "admin"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka.social-network-db:9092"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: social-network-activities
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: activity-service
    version: blue
  ports:
    - port: 8085
      targetPort: 8085