apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: social-network-images
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
      version: blue
  template:
    metadata:
      labels:
        app: image-service
        version: blue
    spec:
      serviceAccountName: image-service-sa
      containers:
        - name: image-service
          image: image-service:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://postgres.social-network-db:5432/spring_microservice_course_db"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis.social-network-db"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-credentials
                  key: password
            - name: SPRING_CLOUD_AWS_S3_ENDPOINT
              value: "http://localstack.social-network-db:4566"
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: social-network-images
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: "http"
spec:
  selector:
    app: image-service
    version: blue
  ports:
    - port: 8082
      targetPort: 8082