apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: social-network-db
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      version: blue
  template:
    metadata:
      labels:
        app: kafka
        version: blue
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.8.0
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                secretKeyRef:
                  name: kafka-credentials
                  key: broker-id
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: social-network-db
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      version: blue
  template:
    metadata:
      labels:
        app: zookeeper
        version: blue
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:6.2.0
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: social-network-db
spec:
  selector:
    app: kafka
    version: blue
  ports:
    - port: 9092
      targetPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: social-network-db
spec:
  selector:
    app: zookeeper
    version: blue
  ports:
    - port: 2181
      targetPort: 2181