apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: social-network-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
      version: blue
  template:
    metadata:
      labels:
        app: localstack
        version: blue
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:latest
          env:
            - name: SERVICES
              value: "s3"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: EDGE_PORT
              value: "4566"
            - name: DEBUG
              value: "1"
          ports:
            - containerPort: 4566
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: social-network-db
spec:
  selector:
    app: localstack
    version: blue
  ports:
    - port: 4566
      targetPort: 4566