apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: social-network-db
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      version: blue
  template:
    metadata:
      labels:
        app: mongodb
        version: blue
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: password
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: database
          command:
            - mongod
            - "--auth"
            - "--bind_ip_all"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
                - mongosh
                - "--eval"
                - "db.adminCommand('ping')"
                - "-u"
                - "$(MONGO_INITDB_ROOT_USERNAME)"
                - "-p"
                - "$(MONGO_INITDB_ROOT_PASSWORD)"
                - "--authenticationDatabase"
                - "admin"
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - mongosh
                - "--eval"
                - "db.adminCommand('ping')"
                - "-u"
                - "$(MONGO_INITDB_ROOT_USERNAME)"
                - "-p"
                - "$(MONGO_INITDB_ROOT_PASSWORD)"
                - "--authenticationDatabase"
                - "admin"
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: social-network-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: social-network-db
spec:
  selector:
    app: mongodb
    version: blue
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None